[project]
name = "sentiment-analysis-fastapi"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "dagshub>=0.5.3",
    "fastapi[standard]>=0.115.8",
    "mlflow>=2.20.1",
    "nltk>=3.9.1",
    "numpy>=2.2.2",
    "uvicorn>=0.34.0",
]
